### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by hakuno** [DataDog/csv_exporter#2]
It always gives some `KeyError` like `series` or `snapshot_url`.

```
[2022-01-19 00:02:40,432] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/code/app.py", line 95, in index
    graph_url = graph_api_response.json()['snapshot_url'].replace('https',
KeyError: 'snapshot_url'
```

Did anybody run that successfully? How?

**Comment by matthieut59** [comment]
indeed not working anymore

**Comment by denisp13** [comment]
upvoting, same result
